module.exports = {
  apps: [
    {
      name: "hrms-api",
      cwd: "./apps/api",
      script: "dist/main.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "3001",
      },
      max_restarts: 10,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      max_memory_restart: "2G",
      error_file: "/var/log/hrms/api-error.log",
      out_file: "/var/log/hrms/api-out.log",
      combine_logs: true,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "hrms-web",
      cwd: "./apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start --port 8080",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "8080",
      },
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "4G",
      error_file: "/var/log/hrms/web-error.log",
      out_file: "/var/log/hrms/web-out.log",
      combine_logs: true,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
