packages:
  - 'backend'
  - 'frontend'
  - 'packages/*'

allowBuilds:
  '@scarf/scarf': true
  '@sentry/cli': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@sentry/cli'
  - '@swc/core'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  multer: 2.2.0
  brace-expansion: 2.1.2
  "@opentelemetry/otlp-transformer>protobufjs": 8.6.6
  "@grpc/proto-loader>protobufjs": 7.6.5
  postcss: 8.5.10
  "@opentelemetry/core": 2.8.0
  js-yaml: 4.3.0
