"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _overview_dashboard from './overview-dashboard.bones.json'
import _overview_bar_graph from './overview-bar-graph.bones.json'
import _overview_area_graph from './overview-area-graph.bones.json'
import _overview_pie_graph from './overview-pie-graph.bones.json'
import _overview_recent_sales from './overview-recent-sales.bones.json'
import _payroll_dashboard from './payroll-dashboard.bones.json'
import _payroll_periods_table from './payroll-periods-table.bones.json'
import _payroll_runs_table from './payroll-runs-table.bones.json'
import _payslips_table from './payslips-table.bones.json'
import _salary_structures_table from './salary-structures-table.bones.json'
import _page_loading from './page-loading.bones.json'
import _table_loading from './table-loading.bones.json'

configureBoneyard({"animate":"pulse"})

registerBones({
  "overview-dashboard": _overview_dashboard,
  "overview-bar-graph": _overview_bar_graph,
  "overview-area-graph": _overview_area_graph,
  "overview-pie-graph": _overview_pie_graph,
  "overview-recent-sales": _overview_recent_sales,
  "payroll-dashboard": _payroll_dashboard,
  "payroll-periods-table": _payroll_periods_table,
  "payroll-runs-table": _payroll_runs_table,
  "payslips-table": _payslips_table,
  "salary-structures-table": _salary_structures_table,
  "page-loading": _page_loading,
  "table-loading": _table_loading,
})
