import { createWorkflow } from './builder';

export const assetRequestWorkflow = createWorkflow({
  id: 'asset-request',
  name: 'Cấp phát & Yêu cầu Thiết bị (Asset Request)',
  entity: 'AssetRequest',
  description: 'Quản lý yêu cầu thiết bị/công cụ làm việc (Laptop, Màn hình, Thiết bị ngoại vi), quy trình phê duyệt và cấp phát thực tế.',
  apiBaseUrl: '/api/v1/asset-management/requests',
  initialState: 'draft',
  states: [
    {
      key: 'draft',
      label: '1. Bản nháp',
      stepNumber: 1,
      variant: 'outline',
      description: 'Nhân viên chọn loại thiết bị, số lượng và lý do cần cấp phát.',
      responsibleActor: {
        role: 'employee',
        label: 'Nhân viên (Người yêu cầu)',
      },
      actionGuidance: 'Kiểm tra thông tin thiết bị và nhấn Nộp yêu cầu để gửi lên cấp quản lý xét duyệt.',
      resultPreview: 'Chuyển sang trạng thái Đang chờ duyệt (Pending Approval).',
    },
    {
      key: 'pending_approval',
      label: '2. Chờ phê duyệt',
      stepNumber: 2,
      variant: 'amber',
      description: 'Yêu cầu đang chờ quản lý trực tiếp hoặc bộ phận phê duyệt tài sản thẩm định.',
      responsibleActor: {
        role: 'manager',
        label: 'Quản lý trực tiếp / Phụ trách duyệt tài sản',
      },
      actionGuidance: 'Xem xét nhu cầu sử dụng và tính cấp thiết của thiết bị trước khi Phê duyệt hoặc Từ chối.',
      resultPreview: 'Chuyển sang trạng thái Đã phê duyệt (Approved) để chuyển sang bộ phận IT/Kho cấp phát.',
    },
    {
      key: 'approved',
      label: '3. Chờ cấp phát thực tế',
      stepNumber: 3,
      variant: 'blue',
      description: 'Yêu cầu đã được duyệt. Bộ phận Quản trị Thiết bị / IT tiến hành xuất kho hoặc gán thiết bị.',
      responsibleActor: {
        role: 'it_admin',
        label: 'Bộ phận IT / Thủ kho Thiết bị',
      },
      actionGuidance: 'Chọn thiết bị vật lý cụ thể (số Serial / Mã tài sản) hoặc xuất số lượng từ kho để bàn giao cho nhân viên.',
      resultPreview: 'Chuyển sang trạng thái Đã cấp phát (Fulfilled) và tạo biên bản bàn giao thiết bị.',
    },
    {
      key: 'fulfilled',
      label: '4. Đã bàn giao & cấp phát',
      stepNumber: 4,
      variant: 'emerald',
      description: 'Thiết bị đã được bàn giao và cập nhật vào danh sách tài sản nhân viên đang nắm giữ.',
      responsibleActor: {
        role: 'completed',
        label: 'Đã hoàn tất quy trình',
      },
      actionGuidance: 'Nhân viên đã nhận thiết bị. Quy trình cấp phát hoàn tất.',
      resultPreview: 'Tài sản được ghi nhận vào danh sách bàn giao của nhân viên.',
      isTerminal: true,
    },
    {
      key: 'rejected',
      label: 'Bị từ chối',
      stepNumber: 2,
      variant: 'destructive',
      description: 'Yêu cầu thiết bị không được chấp thuận.',
      responsibleActor: {
        role: 'employee',
        label: 'Nhân viên (Người yêu cầu)',
      },
      actionGuidance: 'Yêu cầu bị từ chối. Nhân viên có thể liên hệ quản lý để trao đổi thêm.',
      resultPreview: 'Quy trình kết thúc.',
      isTerminal: true,
      isFailure: true,
    },
    {
      key: 'cancelled',
      label: 'Đã hủy bỏ',
      stepNumber: 1,
      variant: 'outline',
      description: 'Yêu cầu đã được hủy bởi người yêu cầu.',
      responsibleActor: {
        role: 'employee',
        label: 'Nhân viên (Người yêu cầu)',
      },
      actionGuidance: 'Yêu cầu này đã bị hủy bỏ.',
      resultPreview: 'Đóng yêu cầu.',
      isTerminal: true,
      isFailure: true,
    },
  ],
  actions: [
    { id: 'submit', label: 'Nộp yêu cầu', targetState: 'pending_approval', actor: 'employee', variant: 'default' },
    { id: 'cancel', label: 'Hủy yêu cầu', targetState: 'cancelled', actor: 'employee', variant: 'destructive' },
    { id: 'approve', label: 'Phê duyệt yêu cầu', targetState: 'approved', actor: 'manager', variant: 'default' },
    { id: 'reject', label: 'Từ chối yêu cầu', targetState: 'rejected', actor: 'manager', variant: 'destructive' },
    { id: 'fulfill', label: 'Xuất kho / Cấp phát thiết bị', targetState: 'fulfilled', actor: 'it_admin', variant: 'default' },
  ],
  transitions: [
    { from: 'draft', to: 'pending_approval', actionId: 'submit', label: 'Nộp yêu cầu', actor: 'Nhân viên' },
    { from: 'draft', to: 'cancelled', actionId: 'cancel', label: 'Hủy yêu cầu', actor: 'Nhân viên' },
    { from: 'pending_approval', to: 'approved', actionId: 'approve', label: 'Phê duyệt', actor: 'Quản lý' },
    { from: 'pending_approval', to: 'rejected', actionId: 'reject', label: 'Từ chối', actor: 'Quản lý' },
    { from: 'approved', to: 'fulfilled', actionId: 'fulfill', label: 'Cấp phát', actor: 'Quản trị IT' },
  ],
});
