import { createWorkflow } from './builder';

export const attendanceWorkflow = createWorkflow({
  id: 'attendance-period',
  name: 'Chu kỳ Chấm công & Khóa Kỳ công (Timekeeping Period)',
  entity: 'AttendancePeriod',
  description: 'Quản lý chu kỳ tổng hợp công, xử lý ngoại lệ đi muộn/về sớm, khóa bảng công và chốt số liệu tính lương.',
  apiBaseUrl: '/api/v1/timekeeping/period-locks',
  initialState: 'draft',
  states: [
    {
      key: 'draft',
      label: '1. Thu thập dữ liệu',
      stepNumber: 1,
      variant: 'outline',
      description: 'Hệ thống đang ghi nhận lượt chấm công hàng ngày và phát hiện các ngoại lệ.',
      responsibleActor: {
        role: 'attendance_specialist',
        label: 'Chuyên viên Chấm công / Team Lead',
        description: 'Kiểm tra và giải quyết ngoại lệ chấm công của nhân viên.',
      },
      actionGuidance: 'Kiểm tra giải quyết ngoại lệ (đi muộn, về sớm, quên check-in), sau đó chuyển sang trạng thái Xét duyệt.',
      resultPreview: 'Bảng công chuyển sang trạng thái Rà soát & Đề xuất (In Review).',
    },
    {
      key: 'in_review',
      label: '2. Rà soát & Đề xuất',
      stepNumber: 2,
      variant: 'amber',
      description: 'Bảng công đang được các cấp quản lý rà soát tổng số ngày làm việc và giờ tăng ca.',
      responsibleActor: {
        role: 'hr_manager',
        label: 'HR Manager / Trưởng bộ phận',
        description: 'Phê duyệt tổng công và xác nhận các giải trình ngoại lệ.',
      },
      actionGuidance: 'Rà soát bảng tổng hợp công, đối chiếu giờ làm thêm (OT) và bấm Khóa bảng công.',
      resultPreview: 'Bảng công được khóa chỉnh sửa và chuyển sang trạng thái Đã khóa (Locked).',
    },
    {
      key: 'locked',
      label: '3. Phê duyệt & Khóa',
      stepNumber: 3,
      variant: 'emerald',
      description: 'Bảng công đã được khóa. Không cho phép sửa đổi chấm công trừ khi mở khóa có lý do.',
      responsibleActor: {
        role: 'payroll_specialist',
        label: 'Kế toán Tiền lương & CFO',
        description: 'Đối soát số liệu công với bảng tính lương.',
      },
      actionGuidance: 'Bảng công đã khóa. Tiến hành đối soát với bảng lương và bấm Chốt kỳ công khi hoàn tất.',
      resultPreview: 'Kỳ công hoàn tất vĩnh viễn và đồng bộ vào Bảng lương.',
    },
    {
      key: 'closed',
      label: '4. Chốt kỳ & Chuyển lương',
      stepNumber: 4,
      variant: 'blue',
      description: 'Kỳ công đã chốt vĩnh viễn. Dữ liệu công đã được chuyển sang Bảng lương.',
      responsibleActor: {
        role: 'completed',
        label: 'Đã hoàn tất quy trình',
      },
      actionGuidance: 'Kỳ công đã chốt thành công. Dữ liệu đã chuyển sang chu kỳ tính lương.',
      resultPreview: 'Dữ liệu được lưu trữ làm căn cứ chi trả lương.',
      isTerminal: true,
    },
  ],
  actions: [
    {
      id: 'review',
      label: 'Chuyển xét duyệt',
      targetState: 'in_review',
      actor: 'attendance_specialist',
      variant: 'default',
      resultPreview: 'Chuyển kỳ công sang bước Rà soát & Đề xuất.',
    },
    {
      id: 'lock',
      label: 'Khóa bảng công',
      targetState: 'locked',
      actor: 'hr_manager',
      variant: 'default',
      resultPreview: 'Khóa chỉnh sửa dữ liệu chấm công.',
    },
    {
      id: 'close',
      label: 'Chốt kỳ công',
      targetState: 'closed',
      actor: 'payroll_specialist',
      variant: 'default',
      resultPreview: 'Chốt kỳ công vĩnh viễn.',
    },
    {
      id: 'unlock',
      label: 'Mở khóa bảng công',
      targetState: 'in_review',
      actor: 'hr_manager',
      variant: 'outline',
      resultPreview: 'Mở khóa để cho phép điều chỉnh dữ liệu chấm công.',
    },
    {
      id: 'reopen',
      label: 'Mở lại kỳ công',
      targetState: 'locked',
      actor: 'payroll_specialist',
      variant: 'outline',
      resultPreview: 'Mở lại kỳ công đã chốt.',
    },
  ],
  transitions: [
    { from: 'draft', to: 'in_review', actionId: 'review', label: 'Chuyển xét duyệt', actor: 'Chuyên viên chấm công' },
    { from: 'in_review', to: 'locked', actionId: 'lock', label: 'Khóa bảng công', actor: 'HR Manager' },
    { from: 'locked', to: 'closed', actionId: 'close', label: 'Chốt kỳ công', actor: 'Kế toán lương' },
    { from: 'locked', to: 'in_review', actionId: 'unlock', label: 'Mở khóa', actor: 'HR Manager' },
    { from: 'closed', to: 'locked', actionId: 'reopen', label: 'Mở lại', actor: 'Kế toán lương' },
  ],
});
