import { createWorkflow } from './builder';

export const employeeLifecycleWorkflow = createWorkflow({
  id: 'employee-lifecycle',
  name: 'Vòng đời Nhân sự (Employee Lifecycle)',
  entity: 'Employee',
  description: 'Quản lý toàn bộ vòng đời nhân sự từ khi thử việc, ký hợp đồng chính thức, điều chuyển đến khi thôi việc và tái tuyển dụng.',
  apiBaseUrl: '/api/v1/employees',
  initialState: 'probation',
  states: [
    {
      key: 'probation',
      label: 'Thử việc',
      stepNumber: 1,
      variant: 'amber',
      description: 'Nhân viên đang trong thời gian thử việc đánh giá năng lực.',
      responsibleActor: {
        role: 'manager_and_hr',
        label: 'Trưởng bộ phận & Phòng Nhân sự',
        description: 'Đánh giá kết quả thử việc để ban hành quyết định chính thức.',
      },
      actionGuidance: 'Theo dõi chỉ số hiệu suất thử việc. Khi đạt yêu cầu, bấm Chuyển chính thức để kích hoạt HĐLĐ chính thức.',
      resultPreview: 'Nhân viên chuyển sang trạng thái Làm việc chính thức (Working) và được hưởng đầy đủ chế độ chính sách.',
    },
    {
      key: 'working',
      label: 'Chính thức',
      stepNumber: 2,
      variant: 'emerald',
      description: 'Nhân viên trong biên chế chính thức của doanh nghiệp.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'Phòng Hành chính Nhân sự',
        description: 'Quản trị hồ sơ, hợp đồng, chấm công và đãi ngộ.',
      },
      actionGuidance: 'Nhân viên đang công tác bình thường. Thực hiện điều chuyển công tác, tạm hoãn hợp đồng hoặc chấm dứt khi có quyết định.',
      resultPreview: 'Cập nhật biến động nhân sự vào hồ sơ lịch sử vòng đời.',
    },
    {
      key: 'leave',
      label: 'Tạm hoãn HĐLĐ',
      stepNumber: 3,
      variant: 'secondary',
      description: 'Nhân viên nghỉ việc riêng dài hạn không hưởng lương hoặc tạm hoãn HĐLĐ.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'Phòng Nhân sự',
        description: 'Theo dõi thời hạn tạm hoãn hợp đồng.',
      },
      actionGuidance: 'Khi hết thời gian tạm hoãn, thực hiện tiếp nhận nhân viên đi làm lại.',
      resultPreview: 'Khôi phục trạng thái làm việc chính thức và quyền truy cập hệ thống.',
    },
    {
      key: 'suspended',
      label: 'Tạm đình chỉ',
      stepNumber: 3,
      variant: 'destructive',
      description: 'Nhân viên đang bị tạm đình chỉ công tác để xác minh kỷ luật.',
      responsibleActor: {
        role: 'disciplinary_committee',
        label: 'Hội đồng Kỷ luật & Ban Giám đốc',
        description: 'Điều tra xác minh sự việc và đưa ra kết luận xử lý.',
      },
      actionGuidance: 'Sau khi có kết luận kỷ luật, bấm Tiếp nhận đi làm lại hoặc Chấm dứt hợp đồng lao động.',
      resultPreview: 'Thực thi quyết định kỷ luật hoặc khôi phục quyền làm việc.',
    },
    {
      key: 'terminated',
      label: 'Đã chấm dứt',
      stepNumber: 4,
      variant: 'outline',
      description: 'Hợp đồng lao động đã thanh lý và chấm dứt.',
      responsibleActor: {
        role: 'recruiter',
        label: 'Bộ phận Tuyển dụng & HR',
        description: 'Lưu trữ hồ sơ và xem xét khả năng tái tuyển dụng.',
      },
      actionGuidance: 'Quan hệ lao động đã kết thúc. Nếu công ty tiếp nhận lại nhân sự này trong tương lai, bấm Tái tuyển dụng.',
      resultPreview: 'Khởi tạo một chu kỳ vòng đời lao động mới cho nhân sự.',
      isTerminal: true,
    },
    {
      key: 'retired',
      label: 'Đã nghỉ hưu',
      stepNumber: 4,
      variant: 'outline',
      description: 'Nhân viên đã hoàn thành thời gian công tác và chuyển sang chế độ hưu trí.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'Phòng Chế độ Chính sách',
        description: 'Hoàn tất hồ sơ bảo hiểm xã hội.',
      },
      actionGuidance: 'Chế độ hưu trí đã được kích hoạt theo quy định pháp luật.',
      resultPreview: 'Hồ sơ chuyển sang trạng thái lưu trữ hưu trí.',
      isTerminal: true,
    },
  ],
  actions: [
    {
      id: 'activate',
      label: 'Chuyển chính thức',
      targetState: 'working',
      actor: 'manager_and_hr',
      variant: 'default',
      resultPreview: 'Trạng thái nhân viên chuyển thành Chính thức (Working).',
    },
    {
      id: 'suspend',
      label: 'Tạm đình chỉ công tác',
      targetState: 'suspended',
      actor: 'disciplinary_committee',
      variant: 'destructive',
      isDestructive: true,
      resultPreview: 'Nhân viên chuyển sang trạng thái Tạm đình chỉ.',
    },
    {
      id: 'resume',
      label: 'Tiếp nhận đi làm lại',
      targetState: 'working',
      actor: 'hr_specialist',
      variant: 'default',
      resultPreview: 'Nhân viên quay lại trạng thái làm việc chính thức.',
    },
    {
      id: 'terminate',
      label: 'Chấm dứt hợp đồng',
      targetState: 'terminated',
      actor: 'hr_specialist',
      variant: 'destructive',
      isDestructive: true,
      resultPreview: 'Hợp đồng bị chấm dứt và chuyển sang quy trình Offboarding.',
    },
    {
      id: 'rehire',
      label: 'Tái tuyển dụng (Rehire)',
      targetState: 'probation',
      actor: 'recruiter',
      variant: 'default',
      resultPreview: 'Tạo chu kỳ lao động mới cho nhân sự.',
    },
  ],
  transitions: [
    { from: 'probation', to: 'working', actionId: 'activate', label: 'Đạt thử việc', actor: 'HR Manager' },
    { from: 'probation', to: 'terminated', actionId: 'terminate', label: 'Không đạt thử việc', actor: 'HR Manager' },
    { from: 'working', to: 'suspended', actionId: 'suspend', label: 'Đình chỉ công tác', actor: 'Hội đồng kỷ luật' },
    { from: 'working', to: 'terminated', actionId: 'terminate', label: 'Thôi việc / Sa thải', actor: 'HR Manager' },
    { from: 'leave', to: 'working', actionId: 'resume', label: 'Đi làm lại', actor: 'HR Specialist' },
    { from: 'suspended', to: 'working', actionId: 'resume', label: 'Hết thời hạn đình chỉ', actor: 'HR Specialist' },
    { from: 'suspended', to: 'terminated', actionId: 'terminate', label: 'Kỷ luật buộc thôi việc', actor: 'HR Specialist' },
    { from: 'terminated', to: 'probation', actionId: 'rehire', label: 'Tái tuyển dụng', actor: 'Tuyển dụng' },
  ],
});
