import { createWorkflow } from './builder';

export const leaveWorkflow = createWorkflow({
  id: 'leave-request',
  name: 'Quy trình Nghỉ phép (Leave Request)',
  entity: 'LeaveRequest',
  description: 'Quản lý việc gửi đơn xin nghỉ, xét duyệt của quản lý và cấn trừ quỹ phép tự động.',
  apiBaseUrl: '/api/v1/leave',
  initialState: 'draft',
  states: [
    {
      key: 'draft',
      label: 'Bản nháp',
      stepNumber: 1,
      variant: 'outline',
      description: 'Đơn mới được tạo và chưa gửi đến người có thẩm quyền.',
      responsibleActor: {
        role: 'employee',
        label: 'Nhân viên (Người tạo đơn)',
        description: 'Kiểm tra ngày nghỉ và lý do trước khi gửi.',
      },
      actionGuidance: 'Kiểm tra lại số ngày nghỉ và lý do, sau đó bấm Gửi duyệt.',
      resultPreview: 'Đơn chuyển sang trạng thái Chờ phê duyệt và gửi thông báo tới Quản lý trực tiếp.',
    },
    {
      key: 'pending',
      label: 'Chờ phê duyệt',
      stepNumber: 2,
      variant: 'secondary',
      description: 'Đơn đang nằm trong hộp thư phê duyệt của Quản lý trực tiếp / Nhân sự.',
      responsibleActor: {
        role: 'manager',
        label: 'Quản lý trực tiếp / HR',
        description: 'Kiểm tra kế hoạch công việc và số dư ngày phép của nhân viên.',
      },
      actionGuidance: 'Xem xét số dư ngày phép, kế hoạch công việc của nhóm để quyết định Phê duyệt hoặc Từ chối đơn.',
      resultPreview: 'Nếu phê duyệt, ngày công sẽ được tính nghỉ hợp lệ. Nếu từ chối, đơn sẽ bị hủy.',
    },
    {
      key: 'approved',
      label: 'Đã phê duyệt',
      stepNumber: 3,
      variant: 'emerald',
      description: 'Đơn đã được phê duyệt thành công.',
      responsibleActor: {
        role: 'system',
        label: 'Hệ thống HRMS & Bảng công',
        description: 'Tự động cấn trừ ngày phép và cập nhật bảng chấm công.',
      },
      actionGuidance: 'Đơn đã duyệt thành công. Quỹ phép đã được trừ tự động.',
      resultPreview: 'Ngày công được ghi nhận đúng chế độ nghỉ.',
      isTerminal: true,
    },
    {
      key: 'rejected',
      label: 'Từ chối',
      stepNumber: 3,
      variant: 'destructive',
      description: 'Đơn bị quản lý từ chối.',
      responsibleActor: {
        role: 'employee',
        label: 'Nhân viên (Người tạo đơn)',
        description: 'Xem lý do từ chối để điều chỉnh ngày nghỉ phù hợp.',
      },
      actionGuidance: 'Đơn xin nghỉ bị từ chối. Nhân viên có thể tạo đơn mới với thời gian phù hợp hơn.',
      resultPreview: 'Quỹ phép không bị cấn trừ.',
      isTerminal: true,
      isFailure: true,
    },
    {
      key: 'cancelled',
      label: 'Đã hủy',
      stepNumber: 3,
      variant: 'outline',
      description: 'Đơn đã bị hủy bởi nhân viên hoặc quản trị viên.',
      responsibleActor: {
        role: 'completed',
        label: 'Quy trình đã kết thúc',
      },
      actionGuidance: 'Đơn đã hủy.',
      resultPreview: 'Không có thay đổi về quỹ phép hay bảng công.',
      isTerminal: true,
    },
  ],
  actions: [
    {
      id: 'submit',
      label: 'Gửi phê duyệt',
      targetState: 'pending',
      actor: 'employee',
      variant: 'default',
      resultPreview: 'Chuyển trạng thái sang Chờ phê duyệt.',
    },
    {
      id: 'approve',
      label: 'Phê duyệt',
      targetState: 'approved',
      actor: 'manager',
      variant: 'default',
      resultPreview: 'Đơn được chấp thuận và trừ phép tự động.',
    },
    {
      id: 'reject',
      label: 'Từ chối',
      targetState: 'rejected',
      actor: 'manager',
      variant: 'destructive',
      resultPreview: 'Đơn bị từ chối kèm lý do.',
    },
    {
      id: 'cancel',
      label: 'Hủy đơn',
      targetState: 'cancelled',
      actor: 'employee',
      variant: 'outline',
      resultPreview: 'Hủy đơn xin nghỉ phép.',
    },
  ],
  transitions: [
    { from: 'draft', to: 'pending', actionId: 'submit', label: 'Gửi đơn', actor: 'Nhân viên' },
    { from: 'draft', to: 'cancelled', actionId: 'cancel', label: 'Hủy bản nháp', actor: 'Nhân viên' },
    { from: 'pending', to: 'approved', actionId: 'approve', label: 'Duyệt đơn', actor: 'Quản lý' },
    { from: 'pending', to: 'rejected', actionId: 'reject', label: 'Từ chối đơn', actor: 'Quản lý' },
    { from: 'pending', to: 'cancelled', actionId: 'cancel', label: 'Hủy đơn đã gửi', actor: 'Nhân viên' },
  ],
});
