import { createWorkflow } from './builder';

export const offboardingWorkflow = createWorkflow({
  id: 'offboarding-process',
  name: 'Quy trình Thôi việc & Bàn giao (Offboarding Process)',
  entity: 'OffboardingProcess',
  description: 'Quản lý bàn giao tài sản, thanh lý hợp đồng, clearance các phòng ban (IT, Tài chính, Hành chính) và quyết toán chế độ thôi việc.',
  apiBaseUrl: '/api/v1/offboarding',
  initialState: 'initiated',
  states: [
    {
      key: 'initiated',
      label: '1. Khởi tạo',
      stepNumber: 1,
      variant: 'outline',
      description: 'Đăng ký nguyện vọng thôi việc hoặc quyết định chấm dứt hợp đồng.',
      responsibleActor: {
        role: 'employee_and_manager',
        label: 'Nhân viên & Quản lý trực tiếp',
      },
      actionGuidance: 'Nhân viên bắt đầu tiếp nhận danh sách bàn giao công việc và hồ sơ.',
      resultPreview: 'Chuyển sang trạng thái Bàn giao công việc (In Progress).',
    },
    {
      key: 'in_progress',
      label: '2. Bàn giao',
      stepNumber: 2,
      variant: 'amber',
      description: 'Thực hiện checklist bàn giao tài liệu, nhiệm vụ và thiết bị làm việc.',
      responsibleActor: {
        role: 'departing_employee',
        label: 'Nhân viên thôi việc',
      },
      actionGuidance: 'Hoàn thành toàn bộ các mục checklist bàn giao bắt buộc.',
      resultPreview: 'Chuyển sang bước Duyệt clearance phòng ban.',
    },
    {
      key: 'clearance_pending',
      label: '3. Duyệt phòng ban',
      stepNumber: 3,
      variant: 'secondary',
      description: 'Các bộ phận IT, Tài chính, Hành chính kiểm tra và phê duyệt xác nhận bàn giao.',
      responsibleActor: {
        role: 'department_heads',
        label: 'Trưởng các bộ phận (IT, Kế toán, Hành chính)',
      },
      actionGuidance: 'Kiểm tra việc thu hồi thiết bị, công nợ và bấm Phê duyệt Clearance.',
      resultPreview: 'Chuyển sang bước Quyết toán chế độ.',
    },
    {
      key: 'awaiting_settlement',
      label: '4. Quyết toán',
      stepNumber: 4,
      variant: 'blue',
      description: 'Tính toán và thanh toán các khoản lương còn lại, phép năm chưa nghỉ và trợ cấp.',
      responsibleActor: {
        role: 'payroll_and_finance',
        label: 'Kế toán Tiền lương & Tài chính',
      },
      actionGuidance: 'Quyết toán các khoản chi trả cuối cùng và bấm Hoàn tất quy trình.',
      resultPreview: 'Hợp đồng lao động chấm dứt vĩnh viễn.',
    },
    {
      key: 'completed',
      label: '5. Hoàn tất thôi việc',
      stepNumber: 5,
      variant: 'emerald',
      description: 'Quy trình thôi việc hoàn tất, hồ sơ chuyển sang trạng thái Đã chấm dứt.',
      responsibleActor: {
        role: 'completed',
        label: 'Đã hoàn tất quy trình',
      },
      actionGuidance: 'Quy trình thôi việc đã kết thúc thành công.',
      resultPreview: 'Hồ sơ nhân viên chuyển sang trạng thái Đã thôi việc (Terminated).',
      isTerminal: true,
    },
    {
      key: 'cancelled',
      label: 'Đã hủy',
      stepNumber: 5,
      variant: 'destructive',
      description: 'Thủ tục thôi việc bị hủy bỏ.',
      responsibleActor: {
        role: 'completed',
        label: 'Quy trình đã kết thúc',
      },
      actionGuidance: 'Thủ tục thôi việc đã hủy.',
      resultPreview: 'Nhân viên tiếp tục làm việc bình thường.',
      isTerminal: true,
      isFailure: true,
    },
  ],
  actions: [
    { id: 'start_clearance', label: 'Bắt đầu duyệt Clearance', targetState: 'clearance_pending', actor: 'departing_employee', variant: 'default' },
    { id: 'approve_clearance', label: 'Xác nhận Clearance', targetState: 'awaiting_settlement', actor: 'department_heads', variant: 'default' },
    { id: 'complete_offboarding', label: 'Hoàn tất quy trình thôi việc', targetState: 'completed', actor: 'payroll_and_finance', variant: 'default' },
    { id: 'cancel_offboarding', label: 'Hủy thôi việc', targetState: 'cancelled', actor: 'employee_and_manager', variant: 'destructive' },
  ],
  transitions: [
    { from: 'initiated', to: 'in_progress', actionId: 'start_clearance', label: 'Bàn giao', actor: 'Nhân viên' },
    { from: 'in_progress', to: 'clearance_pending', actionId: 'start_clearance', label: 'Xin duyệt', actor: 'Nhân viên' },
    { from: 'clearance_pending', to: 'awaiting_settlement', actionId: 'approve_clearance', label: 'Đã duyệt clearance', actor: 'Phòng ban' },
    { from: 'awaiting_settlement', to: 'completed', actionId: 'complete_offboarding', label: 'Hoàn tất', actor: 'Kế toán' },
    { from: 'initiated', to: 'cancelled', actionId: 'cancel_offboarding', label: 'Hủy', actor: 'HR' },
    { from: 'in_progress', to: 'cancelled', actionId: 'cancel_offboarding', label: 'Hủy', actor: 'HR' },
  ],
});
