import { createWorkflow } from './builder';

export const payrollWorkflow = createWorkflow({
  id: 'payroll-run',
  name: 'Bảng tính lương & Chi trả (Payroll Run)',
  entity: 'PayrollRun',
  description: 'Quản lý tính toán phiếu lương từ dữ liệu công, trình duyệt cấp quản lý, phê duyệt và xuất lương cho nhân viên.',
  apiBaseUrl: '/api/v1/payroll/runs',
  initialState: 'draft',
  states: [
    {
      key: 'draft',
      label: '1. Khởi tạo',
      stepNumber: 1,
      variant: 'outline',
      description: 'Bảng lương mới được khởi tạo. Cần tính toán phiếu lương cho từng nhân sự.',
      responsibleActor: {
        role: 'payroll_specialist',
        label: 'Chuyên viên Tiền lương (C&B)',
        description: 'Kiểm tra công thức lương, phụ cấp, giảm trừ gia cảnh và bảo hiểm.',
      },
      actionGuidance: 'Nhấn Tính toán phiếu lương để tổng hợp dữ liệu, sau đó nhấn Trình duyệt để gửi Ban Giám đốc.',
      resultPreview: 'Hệ thống tự động sinh các phiếu lương (payslips) chi tiết.',
    },
    {
      key: 'processing',
      label: '2. Tính toán & Xét duyệt',
      stepNumber: 2,
      variant: 'amber',
      description: 'Bảng lương đang chờ Kế toán trưởng / CFO kiểm tra và phê duyệt.',
      responsibleActor: {
        role: 'cfo',
        label: 'Kế toán trưởng / Giám đốc Tài chính',
        description: 'Đối soát tổng quỹ lương, thuế TNCN và các khoản trích theo lương.',
      },
      actionGuidance: 'Rà soát kỹ số liệu tổng chi phí lương và phiếu lương cá nhân. Nhấn Phê duyệt hoặc Từ chối để hoàn trả tính lại.',
      resultPreview: 'Bảng lương được phê duyệt chính thức hoặc trả về bản nháp.',
    },
    {
      key: 'approved',
      label: '3. Đã phê duyệt',
      stepNumber: 3,
      variant: 'emerald',
      description: 'Bảng lương đã được phê duyệt. Sẵn sàng thực hiện chi trả.',
      responsibleActor: {
        role: 'treasurer',
        label: 'Kế toán Thanh toán / Bộ phận Chi trả',
        description: 'Thực hiện lệnh chuyển khoản và đối soát ngân hàng.',
      },
      actionGuidance: 'Bảng lương đã được phê duyệt. Nhấn Chốt & Xuất lương để phát hành phiếu lương cho nhân viên.',
      resultPreview: 'Phiếu lương được phát hành tới tài khoản nhân viên và khóa chỉnh sửa vĩnh viễn.',
    },
    {
      key: 'posted',
      label: '4. Chốt & Xuất lương',
      stepNumber: 4,
      variant: 'blue',
      description: 'Bảng lương đã chốt vĩnh viễn và không thể chỉnh sửa.',
      responsibleActor: {
        role: 'completed',
        label: 'Đã hoàn tất quy trình',
      },
      actionGuidance: 'Bảng lương đã hoàn tất chi trả và hạch toán vào sổ cái.',
      resultPreview: 'Quy trình tính lương chu kỳ kết thúc.',
      isTerminal: true,
    },
  ],
  actions: [
    {
      id: 'generate',
      label: 'Tính toán phiếu lương',
      targetState: 'draft',
      actor: 'payroll_specialist',
      variant: 'default',
      resultPreview: 'Hệ thống tổng hợp công, phụ cấp và sinh phiếu lương.',
    },
    {
      id: 'request_approval',
      label: 'Trình duyệt bảng lương',
      targetState: 'processing',
      actor: 'payroll_specialist',
      variant: 'outline',
      resultPreview: 'Chuyển bảng lương sang trạng thái Chờ phê duyệt.',
    },
    {
      id: 'approve',
      label: 'Phê duyệt bảng lương',
      targetState: 'approved',
      actor: 'cfo',
      variant: 'default',
      resultPreview: 'Bảng lương được chấp thuận.',
    },
    {
      id: 'reject',
      label: 'Từ chối hoàn trả',
      targetState: 'draft',
      actor: 'cfo',
      variant: 'destructive',
      resultPreview: 'Hoàn trả bảng lương về bản nháp để tính lại.',
    },
    {
      id: 'post',
      label: 'Chốt & Xuất lương',
      targetState: 'posted',
      actor: 'treasurer',
      variant: 'default',
      resultPreview: 'Chốt bảng lương và phát hành phiếu lương cho nhân viên.',
    },
  ],
  transitions: [
    { from: 'draft', to: 'processing', actionId: 'request_approval', label: 'Trình duyệt', actor: 'Chuyên viên lương' },
    { from: 'processing', to: 'approved', actionId: 'approve', label: 'Phê duyệt', actor: 'CFO / Kế toán trưởng' },
    { from: 'processing', to: 'draft', actionId: 'reject', label: 'Từ chối', actor: 'CFO / Kế toán trưởng' },
    { from: 'approved', to: 'posted', actionId: 'post', label: 'Chốt & Xuất lương', actor: 'Thủ quỹ' },
  ],
});
