import { createWorkflow } from './builder';

export const performanceWorkflow = createWorkflow({
  id: 'performance-cycle',
  name: 'Chu kỳ Đánh giá Hiệu suất (Performance Cycle)',
  entity: 'PerformanceCycle',
  description: 'Quản lý 9 giai đoạn từ lập kế hoạch mục tiêu KPI/OKR, tự chấm điểm, quản lý đánh giá, hiệu chỉnh bell-curve đến công bố kết quả.',
  apiBaseUrl: '/api/v1/performance/cycles',
  initialState: 'draft',
  states: [
    {
      key: 'draft',
      label: '1. Khởi tạo',
      stepNumber: 1,
      variant: 'outline',
      description: 'Thiết lập tiêu chí đánh giá và danh sách nhân sự tham gia.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'HR Specialist / Trưởng phòng Nhân sự',
      },
      actionGuidance: 'Kiểm tra cấu hình biểu mẫu và nhấn Mở kế hoạch để bắt đầu.',
      resultPreview: 'Nhân viên có thể bắt đầu đăng ký mục tiêu.',
    },
    {
      key: 'planning',
      label: '2. Lập kế hoạch',
      stepNumber: 2,
      variant: 'amber',
      description: 'Nhân viên thiết lập mục tiêu và người quản lý duyệt kế hoạch.',
      responsibleActor: {
        role: 'employee_and_manager',
        label: 'Nhân viên & Quản lý trực tiếp',
      },
      actionGuidance: 'Sau khi hoàn tất đăng ký mục tiêu, bấm Bắt đầu tự đánh giá.',
      resultPreview: 'Chuyển sang giai đoạn tự chấm điểm.',
    },
    {
      key: 'self_review',
      label: '3. Tự đánh giá',
      stepNumber: 3,
      variant: 'secondary',
      description: 'Nhân viên thực hiện tự chấm điểm kết quả công việc.',
      responsibleActor: {
        role: 'employees',
        label: 'Toàn bộ nhân viên trong chu kỳ',
      },
      actionGuidance: 'Nhân viên hoàn tất bản tự đánh giá và gửi cho quản lý.',
      resultPreview: 'Chuyển sang bước Quản lý đánh giá.',
    },
    {
      key: 'manager_review',
      label: '4. Quản lý đánh giá',
      stepNumber: 4,
      variant: 'amber',
      description: 'Quản lý trực tiếp nhận xét năng lực và cho điểm.',
      responsibleActor: {
        role: 'managers',
        label: 'Quản lý trực tiếp (Direct Managers)',
      },
      actionGuidance: 'Quản lý hoàn tất nhận xét cho nhân viên và chuyển sang phiên hiệu chỉnh.',
      resultPreview: 'Chu kỳ chuyển sang bước Hiệu chỉnh.',
    },
    {
      key: 'calibration',
      label: '5. Hiệu chỉnh',
      stepNumber: 5,
      variant: 'secondary',
      description: 'Cân đối phân bổ xếp loại giữa các bộ phận đảm bảo công bằng.',
      responsibleActor: {
        role: 'hr_committee',
        label: 'Hội đồng Nhân sự (Calibration Committee)',
      },
      actionGuidance: 'Thống nhất phân bổ xếp loại và bấm Trình duyệt.',
      resultPreview: 'Gửi kết quả lên Ban Giám đốc phê duyệt.',
    },
    {
      key: 'ready_for_approval',
      label: '6. Trình duyệt',
      stepNumber: 6,
      variant: 'amber',
      description: 'Kết quả đánh giá đang chờ Ban Giám đốc phê duyệt.',
      responsibleActor: {
        role: 'hr_director',
        label: 'Ban Giám đốc / Giám đốc Nhân sự',
      },
      actionGuidance: 'Xem xét báo cáo tổng hợp và bấm Phê duyệt chu kỳ.',
      resultPreview: 'Kết quả được phê duyệt chính thức.',
    },
    {
      key: 'approved',
      label: '7. Đã phê duyệt',
      stepNumber: 7,
      variant: 'emerald',
      description: 'Kết quả đánh giá đã được phê duyệt.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'Ban Nhân sự',
      },
      actionGuidance: 'Bấm Công bố kết quả để gửi điểm và nhận xét tới nhân viên.',
      resultPreview: 'Phiếu đánh giá hiển thị tới từng nhân sự.',
    },
    {
      key: 'published',
      label: '8. Công bố kết quả',
      stepNumber: 8,
      variant: 'blue',
      description: 'Nhân viên có thể xem kết quả đánh giá cá nhân.',
      responsibleActor: {
        role: 'hr_specialist',
        label: 'Ban Nhân sự',
      },
      actionGuidance: 'Sau khi hoàn thành trao đổi phản hồi, bấm Đóng chu kỳ.',
      resultPreview: 'Chu kỳ đánh giá chính thức đóng.',
    },
    {
      key: 'closed',
      label: '9. Đóng chu kỳ',
      stepNumber: 9,
      variant: 'outline',
      description: 'Chu kỳ hoàn tất và lưu trữ số liệu lịch sử.',
      responsibleActor: {
        role: 'completed',
        label: 'Đã hoàn tất quy trình',
      },
      actionGuidance: 'Chu kỳ đã đóng vĩnh viễn.',
      resultPreview: 'Dữ liệu được lưu trữ làm căn cứ xét thưởng và thăng tiến.',
      isTerminal: true,
    },
  ],
  actions: [
    { id: 'open-planning', label: 'Mở lập kế hoạch mục tiêu', targetState: 'planning', actor: 'hr_specialist', variant: 'default' },
    { id: 'start-self-review', label: 'Bắt đầu tự đánh giá', targetState: 'self_review', actor: 'hr_specialist', variant: 'default' },
    { id: 'start-manager-review', label: 'Chuyển sang Quản lý đánh giá', targetState: 'manager_review', actor: 'hr_specialist', variant: 'default' },
    { id: 'start-calibration', label: 'Mở phiên hiệu chỉnh', targetState: 'calibration', actor: 'hr_specialist', variant: 'default' },
    { id: 'submit-for-approval', label: 'Trình duyệt kết quả', targetState: 'ready_for_approval', actor: 'hr_committee', variant: 'default' },
    { id: 'approve', label: 'Phê duyệt chu kỳ', targetState: 'approved', actor: 'hr_director', variant: 'default' },
    { id: 'publish', label: 'Công bố kết quả', targetState: 'published', actor: 'hr_specialist', variant: 'default' },
    { id: 'close', label: 'Đóng chu kỳ đánh giá', targetState: 'closed', actor: 'hr_specialist', variant: 'outline' },
  ],
  transitions: [
    { from: 'draft', to: 'planning', actionId: 'open-planning', label: 'Mở kế hoạch', actor: 'HR' },
    { from: 'planning', to: 'self_review', actionId: 'start-self-review', label: 'Tự đánh giá', actor: 'HR' },
    { from: 'self_review', to: 'manager_review', actionId: 'start-manager-review', label: 'Quản lý đánh giá', actor: 'HR' },
    { from: 'manager_review', to: 'calibration', actionId: 'start-calibration', label: 'Hiệu chỉnh', actor: 'HR' },
    { from: 'calibration', to: 'ready_for_approval', actionId: 'submit-for-approval', label: 'Trình duyệt', actor: 'Hội đồng' },
    { from: 'ready_for_approval', to: 'approved', actionId: 'approve', label: 'Phê duyệt', actor: 'Giám đốc' },
    { from: 'approved', to: 'published', actionId: 'publish', label: 'Công bố', actor: 'HR' },
    { from: 'published', to: 'closed', actionId: 'close', label: 'Đóng chu kỳ', actor: 'HR' },
  ],
});
