import { createWorkflow } from './builder';

export const recruitmentWorkflow = createWorkflow({
  id: 'recruitment-candidate',
  name: 'Quy trình Tuyển dụng Ứng viên (Recruitment Pipeline)',
  entity: 'CandidateApplication',
  description: 'Quản lý đường ống ứng viên từ khi nhận CV, sàng lọc hồ sơ, phỏng vấn đánh giá, gửi thư mời nhận việc đến khi tiếp nhận chính thức.',
  apiBaseUrl: '/api/v1/recruitment/candidates',
  initialState: 'applied',
  states: [
    {
      key: 'applied',
      label: '1. Nộp hồ sơ',
      stepNumber: 1,
      variant: 'outline',
      description: 'Hồ sơ mới được ứng viên nộp hoặc chuyên viên tuyển dụng nhập.',
      responsibleActor: {
        role: 'recruiter',
        label: 'Chuyên viên Tuyển dụng',
      },
      actionGuidance: 'Kiểm tra CV và tiêu chuẩn tuyển dụng, bấm Chuyển sang Sơ loại.',
      resultPreview: 'Ứng viên chuyển sang bước Sơ loại hồ sơ.',
    },
    {
      key: 'screening',
      label: '2. Sơ loại',
      stepNumber: 2,
      variant: 'amber',
      description: 'Đánh giá độ phù hợp của kinh nghiệm, kỹ năng và mức lương kỳ vọng.',
      responsibleActor: {
        role: 'recruiter',
        label: 'Chuyên viên Tuyển dụng & Hiring Manager',
      },
      actionGuidance: 'Nếu hồ sơ đạt yêu cầu, xếp lịch phỏng vấn và chuyển sang bước Phỏng vấn.',
      resultPreview: 'Ứng viên được mời tham gia phỏng vấn.',
    },
    {
      key: 'interview',
      label: '3. Phỏng vấn',
      stepNumber: 3,
      variant: 'secondary',
      description: 'Hội đồng chuyên môn phỏng vấn và ghi nhận bảng điểm (Scorecard).',
      responsibleActor: {
        role: 'interviewers',
        label: 'Hội đồng Phỏng vấn & Hiring Manager',
      },
      actionGuidance: 'Điền bảng điểm đánh giá năng lực. Nếu đạt, đề xuất gửi thư mời nhận việc.',
      resultPreview: 'Ứng viên được chuyển sang bước Đề nghị nhận việc.',
    },
    {
      key: 'offer',
      label: '4. Đề nghị (Offer)',
      stepNumber: 4,
      variant: 'blue',
      description: 'Soạn thảo và gửi thư mời nhận việc kèm mức lương, đãi ngộ.',
      responsibleActor: {
        role: 'recruiter_and_hr_manager',
        label: 'Chuyên viên Tuyển dụng & HR Manager',
      },
      actionGuidance: 'Theo dõi phản hồi từ ứng viên. Khi ứng viên chấp thuận, bấm Tuyển dụng thành công.',
      resultPreview: 'Kích hoạt quy trình Onboarding nhân viên mới.',
    },
    {
      key: 'hired',
      label: '5. Đã tuyển dụng',
      stepNumber: 5,
      variant: 'emerald',
      description: 'Ứng viên đồng ý offer và chính thức gia nhập tổ chức.',
      responsibleActor: {
        role: 'onboarding_team',
        label: 'Bộ phận Tiếp nhận & Hội nhập (Onboarding)',
      },
      actionGuidance: 'Chuyển thông tin ứng viên sang hồ sơ nhân viên mới.',
      resultPreview: 'Hồ sơ nhân viên được khởi tạo trong hệ thống.',
      isTerminal: true,
    },
    {
      key: 'rejected',
      label: 'Từ chối',
      stepNumber: 5,
      variant: 'destructive',
      description: 'Ứng viên không đạt yêu cầu tuyển dụng.',
      responsibleActor: {
        role: 'completed',
        label: 'Quy trình đã kết thúc',
      },
      actionGuidance: 'Hồ sơ lưu trữ vào cơ sở dữ liệu nhân tài (Talent Pool).',
      resultPreview: 'Gửi thư cảm ơn và từ chối ứng viên.',
      isTerminal: true,
      isFailure: true,
    },
    {
      key: 'withdrawn',
      label: 'Rút hồ sơ',
      stepNumber: 5,
      variant: 'outline',
      description: 'Ứng viên chủ động từ chối hoặc rút hồ sơ.',
      responsibleActor: {
        role: 'completed',
        label: 'Quy trình đã kết thúc',
      },
      actionGuidance: 'Ghi nhận lý do rút hồ sơ.',
      resultPreview: 'Đóng quy trình tuyển dụng đối với ứng viên.',
      isTerminal: true,
    },
  ],
  actions: [
    { id: 'advance_to_screening', label: 'Chuyển sang Sơ loại', targetState: 'screening', actor: 'recruiter', variant: 'default' },
    { id: 'advance_to_interview', label: 'Mời phỏng vấn', targetState: 'interview', actor: 'recruiter', variant: 'default' },
    { id: 'advance_to_offer', label: 'Gửi đề nghị (Offer)', targetState: 'offer', actor: 'recruiter', variant: 'default' },
    { id: 'advance_to_hired', label: 'Xác nhận tuyển dụng', targetState: 'hired', actor: 'recruiter', variant: 'default' },
    { id: 'reject', label: 'Từ chối ứng viên', targetState: 'rejected', actor: 'recruiter', variant: 'destructive' },
    { id: 'withdraw', label: 'Ứng viên rút hồ sơ', targetState: 'withdrawn', actor: 'recruiter', variant: 'outline' },
  ],
  transitions: [
    { from: 'applied', to: 'screening', actionId: 'advance_to_screening', label: 'Sơ loại', actor: 'Tuyển dụng' },
    { from: 'screening', to: 'interview', actionId: 'advance_to_interview', label: 'Phỏng vấn', actor: 'Tuyển dụng' },
    { from: 'interview', to: 'offer', actionId: 'advance_to_offer', label: 'Offer', actor: 'Tuyển dụng' },
    { from: 'offer', to: 'hired', actionId: 'advance_to_hired', label: 'Tuyển dụng', actor: 'Tuyển dụng' },
    { from: 'applied', to: 'rejected', actionId: 'reject', label: 'Loại hồ sơ', actor: 'Tuyển dụng' },
    { from: 'screening', to: 'rejected', actionId: 'reject', label: 'Không đạt sơ loại', actor: 'Tuyển dụng' },
    { from: 'interview', to: 'rejected', actionId: 'reject', label: 'Không đạt phỏng vấn', actor: 'Hội đồng' },
    { from: 'offer', to: 'rejected', actionId: 'reject', label: 'Hủy offer', actor: 'Tuyển dụng' },
  ],
});
