import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { fileStatusEnum } from "./enums";
import { users } from "../identity/tables";

export const files = pgTable(
  "files",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: text("key").notNull().unique(),
    bucket: text("bucket").notNull(),
    ownerType: text("owner_type").notNull(),
    ownerId: uuid("owner_id").notNull(),
    purpose: text("purpose").notNull(),
    status: fileStatusEnum("status").notNull().default("temp"),
    mimeType: text("mime_type"),
    sizeBytes: integer("size_bytes"),
    sha256: text("sha256"),
    uploadedBy: uuid("uploaded_by").references(() => users.id, {
      onDelete: "set null",
    }),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    finalizeAttempts: integer("finalize_attempts").notNull().default(0),
    lastFinalizeAt: timestamp("last_finalize_at", { withTimezone: true }),
    lastFinalizeError: text("last_finalize_error"),
    // Thumbnail reference (generated by image processor)
    thumbnailKey: text("thumbnail_key"),
    // Legal hold prevents deletion
    legalHoldAt: timestamp("legal_hold_at", { withTimezone: true }),
    // Retention period in days (null = indefinite)
    retentionDays: integer("retention_days"),
    // Antivirus scan tracking — additive layer on top of status
    scanStatus: text("scan_status"), // null, "pending", "scanning", "clean", "infected"
    scanResult: text("scan_result"), // virus name or details from scanner
    scannedAt: timestamp("scanned_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => ({
    idxKey: uniqueIndex("idx_files_key").on(table.key),
    idxOwner: index("idx_files_owner").on(
      table.ownerType,
      table.ownerId,
      table.status,
    ),
    idxStatusExpires: index("idx_files_status_expires").on(
      table.status,
      table.expiresAt,
    ),
    idxSha256Dedup: index("idx_files_sha256_dedup").on(
      table.sha256,
      table.ownerId,
      table.purpose,
      table.status,
    ),
  }),
);

export const pendingFileFinalizations = pgTable(
  "pending_file_finalizations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fileId: uuid("file_id")
      .notNull()
      .references(() => files.id, { onDelete: "cascade" }),
    ownerType: text("owner_type").notNull(),
    ownerId: uuid("owner_id").notNull(),
    targetKey: text("target_key").notNull(),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    nextRetryAt: timestamp("next_retry_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => ({
    idxRetry: index("idx_pff_next_retry").on(table.nextRetryAt, table.attempts),
    idxFileId: index("idx_pff_file_id").on(table.fileId),
  }),
);
